#  Introducción a Numpy

In [16]:
import csv
import numpy as np

In [2]:
data_ndarray = np.array([10, 20, 30], dtype=int)

In [3]:
print(data_ndarray)

[10 20 30]


In [4]:
print(type(data_ndarray))

<class 'numpy.ndarray'>


In [6]:
data_ndarray02 = np.array('10 20 30'.split(), dtype=int)

In [8]:
print(data_ndarray02)

[10 20 30]


```python
pickup_year,pickup_month,pickup_day,pickup_dayofweek
2016,1,1,5
2016,1,1,5
2016,1,1,5
2016,1,1,5
```

In [17]:
with open('nyc_taxis.csv', 'r') as f:
    header_taxi = [*next(csv.reader(f))]
    taxi_list = [*csv.reader(f)]

In [19]:
print(taxi_list[:5])

[['2016', '1', '1', '5', '0', '2', '4', '21.00', '2037', '52.00', '0.80', '5.54', '11.65', '69.99', '1'], ['2016', '1', '1', '5', '0', '2', '1', '16.29', '1520', '45.00', '1.30', '0.00', '8.00', '54.30', '1'], ['2016', '1', '1', '5', '0', '2', '6', '12.70', '1462', '36.50', '1.30', '0.00', '0.00', '37.80', '2'], ['2016', '1', '1', '5', '0', '2', '6', '8.70', '1210', '26.00', '1.30', '0.00', '5.46', '32.76', '1'], ['2016', '1', '1', '5', '0', '2', '6', '5.56', '759', '17.50', '1.30', '0.00', '0.00', '18.80', '2']]


In [20]:
print(header_taxi)

['pickup_year', 'pickup_month', 'pickup_day', 'pickup_dayofweek', 'pickup_time', 'pickup_location_code', 'dropoff_location_code', 'trip_distance', 'trip_length', 'fare_amount', 'fees_amount', 'tolls_amount', 'tip_amount', 'total_amount', 'payment_type']


In [24]:
converted_taxi_list = [[float(element) for element in row] for row in taxi_list]
print(converted_taxi_list[:5])

[[2016.0, 1.0, 1.0, 5.0, 0.0, 2.0, 4.0, 21.0, 2037.0, 52.0, 0.8, 5.54, 11.65, 69.99, 1.0], [2016.0, 1.0, 1.0, 5.0, 0.0, 2.0, 1.0, 16.29, 1520.0, 45.0, 1.3, 0.0, 8.0, 54.3, 1.0], [2016.0, 1.0, 1.0, 5.0, 0.0, 2.0, 6.0, 12.7, 1462.0, 36.5, 1.3, 0.0, 0.0, 37.8, 2.0], [2016.0, 1.0, 1.0, 5.0, 0.0, 2.0, 6.0, 8.7, 1210.0, 26.0, 1.3, 0.0, 5.46, 32.76, 1.0], [2016.0, 1.0, 1.0, 5.0, 0.0, 2.0, 6.0, 5.56, 759.0, 17.5, 1.3, 0.0, 0.0, 18.8, 2.0]]


In [25]:
taxi = np.array(converted_taxi_list)

In [26]:
print(taxi)

[[2.016e+03 1.000e+00 1.000e+00 ... 1.165e+01 6.999e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 8.000e+00 5.430e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 0.000e+00 3.780e+01 2.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 5.000e+00 6.334e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 8.950e+00 4.475e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 0.000e+00 5.484e+01 2.000e+00]]


In [33]:
print(np.array(taxi_list[:5], dtype=float))

[[2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 4.000e+00
  2.100e+01 2.037e+03 5.200e+01 8.000e-01 5.540e+00 1.165e+01 6.999e+01
  1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 1.000e+00
  1.629e+01 1.520e+03 4.500e+01 1.300e+00 0.000e+00 8.000e+00 5.430e+01
  1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 6.000e+00
  1.270e+01 1.462e+03 3.650e+01 1.300e+00 0.000e+00 0.000e+00 3.780e+01
  2.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 6.000e+00
  8.700e+00 1.210e+03 2.600e+01 1.300e+00 0.000e+00 5.460e+00 3.276e+01
  1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 6.000e+00
  5.560e+00 7.590e+02 1.750e+01 1.300e+00 0.000e+00 0.000e+00 1.880e+01
  2.000e+00]]


In [34]:
print(taxi.shape)

(2013, 15)


In [37]:
print(taxi.shape[1])

15


In [41]:
num_rows, num_cols = taxi.shape

In [42]:
print(num_rows)

2013


In [44]:
print(taxi[:5])


[[2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 4.000e+00
  2.100e+01 2.037e+03 5.200e+01 8.000e-01 5.540e+00 1.165e+01 6.999e+01
  1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 1.000e+00
  1.629e+01 1.520e+03 4.500e+01 1.300e+00 0.000e+00 8.000e+00 5.430e+01
  1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 6.000e+00
  1.270e+01 1.462e+03 3.650e+01 1.300e+00 0.000e+00 0.000e+00 3.780e+01
  2.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 6.000e+00
  8.700e+00 1.210e+03 2.600e+01 1.300e+00 0.000e+00 5.460e+00 3.276e+01
  1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 6.000e+00
  5.560e+00 7.590e+02 1.750e+01 1.300e+00 0.000e+00 0.000e+00 1.880e+01
  2.000e+00]]


In [45]:
row_0 = taxi[0]
print(row_0)

[2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 4.000e+00
 2.100e+01 2.037e+03 5.200e+01 8.000e-01 5.540e+00 1.165e+01 6.999e+01
 1.000e+00]


In [46]:
row21_col5 = taxi[21, 5]
print(row21_col5)

4.0


In [47]:
rows_391_to_500 = taxi[391:501]
print(rows_391_to_500)

[[2.016e+03 1.000e+00 2.000e+00 ... 0.000e+00 2.630e+01 2.000e+00]
 [2.016e+03 1.000e+00 2.000e+00 ... 3.000e+00 3.030e+01 1.000e+00]
 [2.016e+03 1.000e+00 2.000e+00 ... 6.670e+00 4.001e+01 1.000e+00]
 ...
 [2.016e+03 1.000e+00 4.000e+00 ... 0.000e+00 5.534e+01 2.000e+00]
 [2.016e+03 1.000e+00 4.000e+00 ... 3.090e+00 1.339e+01 1.000e+00]
 [2.016e+03 1.000e+00 4.000e+00 ... 4.000e+00 2.680e+01 1.000e+00]]


In [49]:
columns_1_4_7 = taxi[:, [1, 4, 7]]
print(columns_1_4_7)

[[ 1.    0.   21.  ]
 [ 1.    0.   16.29]
 [ 1.    0.   12.7 ]
 ...
 [ 6.    5.   17.48]
 [ 6.    5.   12.76]
 [ 6.    5.   17.54]]


In [50]:
print(columns_1_4_7.shape)

(2013, 3)


In [52]:
row_99_columns_5_to_8 = taxi[99, 5:9 ]
print(row_99_columns_5_to_8)

rows_100_to_200_column_14 = taxi[100:201, 14]
print(rows_100_to_200_column_14)

[   2.      4.     20.91 1744.  ]
[2. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 2. 2. 2. 1. 2. 1. 2. 1. 1. 2. 2.
 2. 1. 1. 2. 1. 2. 1. 1. 2. 2. 1. 1. 2. 2. 1. 1. 1. 2. 1. 1. 1. 2. 2. 2.
 2. 2. 1. 4. 2. 1. 2. 1. 2. 2. 2. 2. 1. 1. 2. 1. 2. 2. 2. 2. 1. 2. 2. 1.
 2. 1. 2. 1. 2. 2. 1. 1. 1. 1. 2. 1. 1. 2. 2. 1. 1. 2. 2. 1. 1. 2. 1. 1.
 1. 1. 1. 2. 2.]


In [54]:
fare_amount = taxi[:,9]
fees_amount = taxi[:,10]

print(fare_amount.shape)
print(fees_amount.shape)

(2013,)
(2013,)


In [56]:
print(fare_amount)
print(fees_amount)

[52.  45.  36.5 ... 52.  34.5 48. ]
[0.8 1.3 1.3 ... 0.8 1.3 1.3]


In [57]:
fare_and_fees = fare_amount + fees_amount
print(fare_and_fees)

[52.8 46.3 37.8 ... 52.8 35.8 49.3]


In [59]:
trip_distance_miles = taxi[:,7]
trip_length_second = taxi[:, 8]

trip_length_hours = np.divide(trip_length_second, 3600)
print(trip_length_hours)


[0.56583333 0.42222222 0.40611111 ... 0.78388889 0.30083333 0.47527778]


In [62]:
trip_mph = trip_distance_miles / trip_length_hours
print(trip_mph)

[37.11340206 38.58157895 31.27222982 ... 22.29907867 42.41551247
 36.90473407]


In [63]:
mph_min = trip_mph.min()
mph_max = trip_mph.max()
mph_mean = trip_mph.mean()

print(mph_min)
print(mph_max)
print(mph_mean)


0.0
82800.0
169.98315083655157


In [66]:
print(np.median(trip_mph))

24.180945853324197


In [67]:
taxi_first_five = taxi[:5]

fare_components = taxi_first_five[:, 9:13]

print(fare_components)

[[52.    0.8   5.54 11.65]
 [45.    1.3   0.    8.  ]
 [36.5   1.3   0.    0.  ]
 [26.    1.3   0.    5.46]
 [17.5   1.3   0.    0.  ]]


In [70]:
fare_sums = fare_components.sum(axis=1)
print(fare_sums)|

[69.99 54.3  37.8  32.76 18.8 ]


In [72]:
print(taxi_first_five[:, 13])

[69.99 54.3  37.8  32.76 18.8 ]
