<center><h1>Indexación Booleana</h1></center>

<h2>1. Lectura de archivos CSV con NumPy</h2>
<br>
<p>NumPy facilita la selección de datos e incluye una serie de funciones que simplifican el cálculo de estadísticas en los diferentes ejes (o dimensiones). </p>
<p>Por ejemplo, digamos que queremos saber cuántos <a href="https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page" target="_blank ">viajes en taxi</a> que los pasajeros hicieron cada mes? ¿O qué aeropuerto es el más concurrido? Para ello, aprenderemos una nueva técnica: <strong>Indización booleana</strong>. Antes de comenzar con la indexación booleana, veamos nuestros datos. <a href="https://drive.google.com/file/d/1O62oOCpvH4pW-TEfuCB7QnUoQgVCZRfo/view?usp=sharing">Puedes descargar los datos aquí</a></p>
<p>Estas son las primeras cinco filas de nuestros datos con etiquetas de columna:</p>

<table>
<thead>
<tr>
<th>pickup_year</th>
<th>pickup_month</th>
<th>pickup_day</th>
<th>pickup_dayofweek</th>
<th>pickup_time</th>
<th>pickup_location_code</th>
<th>dropoff_location_code</th>
<th>trip_distance</th>
<th>trip_length</th>
<th>fare_amount</th>
<th>fees_amount</th>
<th>tolls_amount</th>
<th>tip_amount</th>
<th>total_amount</th>
<th>payment_type</th>
</tr>
</thead>
<tbody>
<tr>
<td>2016</td>
<td>1</td>
<td>1</td>
<td>5</td>
<td>0</td>
<td>2</td>
<td>4</td>
<td>21.00</td>
<td>2037</td>
<td>52.0</td>
<td>0.8</td>
<td>5.54</td>
<td>11.65</td>
<td>69.99</td>
<td>1</td>
</tr>
<tr>
<td>2016</td>
<td>1</td>
<td>1</td>
<td>5</td>
<td>0</td>
<td>2</td>
<td>1</td>
<td>16.29</td>
<td>1520</td>
<td>45.0</td>
<td>1.3</td>
<td>0.00</td>
<td>8.00</td>
<td>54.30</td>
<td>1</td>
</tr>
<tr>
<td>2016</td>
<td>1</td>
<td>1</td>
<td>5</td>
<td>0</td>
<td>2</td>
<td>6</td>
<td>12.70</td>
<td>1462</td>
<td>36.5</td>
<td>1.3</td>
<td>0.00</td>
<td>0.00</td>
<td>37.80</td>
<td>2</td>
</tr>
<tr>
<td>2016</td>
<td>1</td>
<td>1</td>
<td>5</td>
<td>0</td>
<td>2</td>
<td>6</td>
<td>8.70</td>
<td>1210</td>
<td>26.0</td>
<td>1.3</td>
<td>0.00</td>
<td>5.46</td>
<td>32.76</td>
<td>1</td>
</tr>
<tr>
<td>2016</td>
<td>1</td>
<td>1</td>
<td>5</td>
<td>0</td>
<td>2</td>
<td>6</td>
<td>5.56</td>
<td>759</td>
<td>17.5</td>
<td>1.3</td>
<td>0.00</td>
<td>0.00</td>
<td>18.80</td>
<td>2</td>
</tr>
</tbody>
</table>

<p>A continuación se muestra información sobre las columnas seleccionadas del conjunto de datos:</p>
<ul>
<li><code>pickup_year</code>: el año del viaje</li>
<li><code>pickup_month</code>: el mes del viaje (enero es <code>1</code>, diciembre es <code>12</code>)</li>
<li><code>pickup_day</code>: el día del mes del viaje</li>
<li><code>pickup_location_code</code>: el aeropuerto o <a href="https://en.wikipedia.org/wiki/Boroughs_of_New_York_City" target="_blank">distrito</a> donde comenzó el viaje </li>
<li><code>dropoff_location_code</code>: el aeropuerto o distrito donde finalizó el viaje</li>
<li><code>trip_distance</code>: la distancia del viaje en millas</li>
<li><code>trip_length</code>: la duración del viaje en segundos</li>
<li><code>fare_amount</code>: la tarifa base del viaje, en dólares</li>
<li><code>total_amount</code>: el monto total cobrado al pasajero, incluidas todas las tarifas, peajes y propinas</li>
</ul>
<p>Puede encontrar información sobre todas las columnas en el <a href="https://s3.amazonaws.com/dq-content/290/nyc_taxi_data_dictionary.md" target="_blank">diccionario de datos</a>. </p>
<p>Ahora, aprendamos a usar el <a href="https://numpy.org/doc/stable/reference/generated/numpy.genfromtxt.html" target= Función "_blank"><code>numpy.genfromtxt()</code></a> para leer archivos en NumPy ndarrays. Esta es la sintaxis simplificada de la función y una explicación de los dos parámetros:</p>


```python
np.genfromtxt(filename, delimiter=None)
```

<div>
<ul>
<li><code>filename</code>: un argumento posicional, generalmente una cadena que representa la ruta al archivo de texto para leer</li>
<li><code>delimiter</code>: un argumento con nombre, que especifica la cadena utilizada para separar cada valor</li>
</ul>
<p>En este caso, debido a que tenemos un archivo CSV, el delimitador es una coma. Así es como lo leeríamos en un archivo llamado <code>data.csv</code>:</p>
</div>

```python
data = np.genfromtxt('data.csv', delimiter=',')
```

<div>
<p>Vamos a leer nuestro archivo <code>nyc_taxis.csv</code> en NumPy a continuación.</p></div>

<h3>Ejercicio</h3>

<ol>
<li>Importe la biblioteca NumPy y asígnele el alias <code>np</code>.</li>
<li>Utilice la función <code>numpy.genfromtxt()</code> para leer el archivo <code>nyc_taxis.csv</code> en NumPy. Asigne el resultado a <code>taxi</code>.</li>
<li>Utilice el atributo <a href="https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.ndarray.shape.html#numpy.ndarray.shape" target="_blank "><code>ndarray.shape</code> </a> para asignar la dimensión de <code>taxi</code> a <code>taxi_shape</code>.</li>
<li>Imprima las variables para ver el ndarray <code>taxi</code> y su dimensión después de ejecutar su código.</li>
</ol>

In [ ]:
np.set_printoptions(suppress=True)

<h2>2. Lectura de archivos CSV con NumPy Continuación </h2>
<br>
<div><p>En el ejercicio anterior, usamos la función <code>numpy.genfromtxt()</code> para leer el archivo <code>nyc_taxis.csv</code> en NumPy, lo que nos permitió importar el datos de forma rápida y eficiente:</p>
</div>

```python
# import nyc_taxi.csv as a list of lists
f = open("nyc_taxis.csv", "r")
taxi_list = list(csv.reader(f))

# remove the header row
taxi_list = taxi_list[1:]

# convert all values to floats
converted_taxi_list = []
for row in taxi_list:
    converted_row = []
    for item in row:
        converted_row.append(float(item))
    converted_taxi_list.append(converted_row)

# start writing your code below this comment
taxi = np.array(converted_taxi_list)
```

<div>
<p>Convertimos todos los valores en flotantes antes de convertir la lista de listas en un ndarray. Esto se debe a que los ndarrays NumPy solo pueden contener <em>un tipo de datos</em>.</p>
<p>No tuvimos que completar este paso en el ejercicio anterior porque cuando <code>numpy.genfromtxt()</code> lee un archivo, intenta determinar el tipo de datos del archivo mirando los valores . </p>
<p>Podemos usar el <a href="http://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.ndarray.dtype.html#numpy.ndarray.dtype" target= "_blank"><code>ndarray.dtype</code> atributo</a> para ver el tipo de datos interno.</p>
</div>

```python
print(taxi.dtype)
```

```python
float64
```

<div>
<p>NumPy eligió el tipo <code>float64</code>, ya que permitirá leer la mayoría de los valores de nuestro CSV. Puede pensar en el tipo <code>float64</code> de NumPy como idéntico al tipo <code>float</code> de Python (el "64" se refiere al número de <a href="https://en.wikipedia. org/wiki/Bit" target="_blank">bits</a> utilizados para almacenar el valor subyacente).</p>
<p>Si revisamos los resultados del ejercicio anterior, podemos ver que <code>taxi</code> contiene casi todos los números excepto un valor que no hemos visto antes: <code>nan</code>. </p>
</div>

```python
[[   nan    nan    nan ...,    nan    nan    nan]
 [  2016      1      1 ...,  11.65  69.99      1]
 [  2016      1      1 ...,      8   54.3      1]
 ..., 
 [  2016      6     30 ...,      5  63.34      1]
 [  2016      6     30 ...,   8.95  44.75      1]
 [  2016      6     30 ...,      0  54.84      2]]
```

<div>
<p>NaN es un acrónimo de <strong>No es un número</strong>; literalmente significa que el valor no se puede almacenar como un número. Es similar a (y a menudo se lo denomina) valor nulo, como el <a href="https://docs.python.org/3/library/constants.html#None" target="_blank"><code de Python >Ninguno</code> constante</a>.</p>
<p>Normalmente vemos NaN cuando falta un valor, pero en este caso, tenemos valores NaN porque la primera línea de nuestro archivo CSV contiene los nombres de cada columna. NumPy no puede convertir valores de cadena como <code>pickup_year</code> en el tipo de datos <code>float64</code>.</p>
<p>Por ahora, necesitamos eliminar esta fila de encabezado de nuestro ndarray. Podemos hacer esto de la misma manera que lo haríamos si nuestros datos estuvieran en una lista de listas:</p>
</div>

```python
taxi = taxi[1:]

```

<div>
<p>Alternativamente, podemos pasar un parámetro adicional, <code>skip_header</code>, a la función <code>numpy.genfromtxt()</code>. El parámetro <code>skip_header</code> acepta un número entero: el número de filas desde el inicio del archivo para omitir. Tenga en cuenta que debido a que este número entero debe ser el <em>número de filas</em> y no el índice, omitir la primera fila requeriría un valor de <code>1</code>, no <code>0</code> .</p></div>

<h3>Ejercicio</h3>
<ol>
<li>Utilice la función <code>numpy.genfromtxt()</code> para volver a leer el archivo <code>nyc_taxis.csv</code> en NumPy, pero esta vez, omita la primera fila. Asigne el resultado a <code>taxi</code>.</li>
<li>Asigne la forma de <code>taxi</code> a <code>taxi_shape</code>.</li>
<li>Use el inspector de variables debajo del cuadro de código para ver el ndarray <code>taxi</code> y su forma después de haber ejecutado su código.</li>
</ol>

In [ ]:
print(taxi_shape)

<h2>3. Matrices booleanas</h2>
<br>
<div><p>Ahora, centrémonos en posiblemente el método más poderoso para indexar datos: la matriz booleana. Una <strong>matriz booleana</strong>, como sugiere su nombre, es una matriz de valores booleanos. A veces llamamos a las matrices booleanas <strong>vectores booleanos</strong> o <strong>máscaras booleanas</strong>.</p>
<p>Puede recordar que el tipo booleano (o <code>bool</code>) es un tipo integrado de Python que puede ser uno de dos valores únicos:</p>
<ul>
<li><código>Verdadero</código></li>
<li><código>Falso</código></li>
</ul>
<p>También usamos valores booleanos cuando trabajamos con <a href="https://docs.python.org/3.4/library/stdtypes.html#comparisons" target="_blank">operadores de comparación</a> de Python como <code>==</code> (igual) <code>&gt;</code> (mayor que), <code>&lt;</code> (menor que), <code>!=</code> ( no es igual). A continuación se muestran algunos ejemplos de operaciones booleanas simples:</p>
</div>

```python
print(type(3.5) == float)
True

print(5 > 6)
False
```



<div>
<p>Cuando hablamos de matemática vectorial, una operación entre un ndarray y un solo valor da como resultado un nuevo ndarray:</p>
</div>

```python
print(np.array([2,4,6,8]) + 10)
[12 14 16 18]
```

<div>
<p>La operación <code>+ 10</code> se aplica a cada valor de la matriz.</p>
<p>Ahora, veamos qué sucede cuando realizamos una <em>operación booleana</em> entre un ndarray y un solo valor:</p>
</div>

```python
print(np.array([2,4,6,8]) < 5)
[ True  True False False]
```

<div>
<p>Ocurre un patrón similar: cada valor de la matriz se compara con cinco. Si el valor es menor que cinco, se devuelve <code>True</code>. De lo contrario, se devuelve <code>False</code>.</p>
<p><img src="https://s3.amazonaws.com/dq-content/290/vectorized_bool.svg" alt="Operación booleana vectorizada" width="600" height="400"></p>
<p>Practiquemos usando operaciones booleanas vectorizadas para crear algunas matrices booleanas.</p></div>

<h3>Ejercicio</h3>

<ol>
<li>Utilice operaciones booleanas vectorizadas para hacer lo siguiente:<ul>
<li>Evalúa si los elementos de la matriz <code>a</code> son menores que <code>3</code>. Asigne el resultado a <code>a_bool</code>.</li>
<li>Evalúa si los elementos en el arreglo <code>b</code> son iguales a <code>"blue"</code>. Asigne el resultado a <code>b_bool</code>.</li>
<li>Evalúa si los elementos de la matriz <code>c</code> son mayores que <code>100</code>. Asigne el resultado a <code>c_bool</code>.</li>
</ul>
</li>
<li>Una vez que haya ejecutado su código, imprima las variables para ver el resultado.</li>
</ol>

In [ ]:
# conver to ndarray
a = [1, 2, 3, 4, 5]
b = ["blue", "blue", "red", "blue"]
c = [80.0, 103.4, 96.9, 200.3]

<h2>4. Indexación booleana con ndarrays 1D</h2>
<br>
<div><p>Aprendimos cómo crear matrices booleanas usando operaciones booleanas vectorizadas. A continuación, aprenderemos a <em>indexar</em> (o seleccionar) mediante matrices booleanas, conocidas como <strong>indexación booleana</strong>. Usemos uno de los ejemplos de la sección anterior.</p>
<p><img src="https://s3.amazonaws.com/dq-content/290/1d_bool_1.svg" alt="Indización booleana 1D ndarrays 1" width="600" height="400"></p>
<p>Para indexar usando nuestra nueva matriz booleana, simplemente la insertamos entre corchetes, tal como lo haríamos con nuestras otras técnicas de selección:</p>
<p><img src="https://s3.amazonaws.com/dq-content/290/1d_bool_2.svg" alt="Indización booleana 1D ndarrays 2" width="600" height="400"></p>
<p>La matriz booleana actúa como un filtro, de modo que los valores correspondientes a <code>True</code> pasan a formar parte del resultado y los valores correspondientes a <code>False</code> se eliminan.</p>
<p>Utilicemos la indexación booleana para confirmar la cantidad de viajes en taxi en nuestro conjunto de datos del mes de enero. Primero, seleccionemos solo la columna <code>pickup_month</code>, que es la segunda columna en el ndarray:</p>
</div>

```python
pickup_month = taxi[:,1]
```

<div>
<p>A continuación, usamos una operación booleana para crear una matriz booleana, donde el valor <code>1</code> corresponde a enero:</p>
</div>

```python
january_bool = pickup_month == 1
```

<div>
<p>Luego, usamos la nueva matriz booleana para seleccionar solo los elementos de <code>pickup_month</code> que tienen un valor de <code>1</code>:</p>
</div>

```python
january = pickup_month[january_bool]
```

<div>
<p>Finalmente, usamos el atributo <code>.shape</code> para determinar cuántos artículos hay en nuestro ndarray de <code>enero</code>, que es igual a la cantidad de viajes en taxi desde el mes de enero. . Usaremos <code>[0]</code> para extraer el valor de la tupla devuelta por <code>.shape</code>:</p>
</div>

```python
january_rides = january.shape[0]
print(january_rides)
```

```python
800
```

<div>
<p>Hay 800 viajes en nuestro conjunto de datos desde el mes de enero. Practiquemos la indexación booleana y determinemos la cantidad de viajes en nuestro conjunto de datos para febrero.</p></div>

<h3>Ejercicio</h3>

<ol>
<li>Calcule el número de viajes en el ndarray de <code>taxi</code> de febrero:<ul>
<li>Cree una matriz booleana, <code>february_bool</code>, que evalúe si los elementos en <code>pickup_month</code> son iguales a <code>2</code>.</li>
<li>Utilice la matriz booleana <code>february_bool</code> para indexar <code>pickup_month</code>. Asigne el resultado a <code>febrero</code>.</li>
<li>Use el atributo <code>ndarray.shape</code> para encontrar el número de artículos en <code>febrero</code>. Asigne el resultado a <code>february_rides</code>.</li>
</ul>
</li>
<li>Una vez que haya ejecutado su código, imprima las variables para ver la cantidad de viajes de febrero.</li>
</ol>

In [ ]:
print(february_rides)

<h2>5. Indexación booleana con ndarrays 2D</h2>
<br>
<div><p>Al trabajar con ndarrays 2D, puede usar la indexación booleana en combinación con otros métodos de indexación. La única limitación es que la matriz booleana debe tener la misma longitud que la dimensión que está indexando. Veamos algunos ejemplos:</p>
<p><img src="https://s3.amazonaws.com/dq-content/290/bool_dims_updated.svg" alt="Indización booleana 1D ndarrays 2" width="600" height="400"></p>
<p>Debido a que una matriz booleana no contiene información sobre su creación, podemos usar una matriz booleana creada a partir de una sola columna de nuestra matriz para indexar toda la matriz.</p>
<p>Usemos lo que hemos aprendido para analizar la velocidad promedio de los viajes. Veamos si hay algún problema con los datos. Calculamos la velocidad de viaje promedio de la siguiente manera:</p>
</div>

```python
# calculate the average speed
trip_mph = taxi[:,7] / (taxi[:,8] / 3600)
```

<div>
<p>A continuación, buscaremos viajes con una velocidad promedio superior a 20 000 mph:</p>
</div>

```python
# create a boolean array for trips with average
# speeds greater than 20,000 mph
trip_mph_bool = trip_mph > 20000

# use the boolean array to select the rows for
# those trips, and the pickup_location_code,
# dropoff_location_code, trip_distance, and
# trip_length columns
trips_over_20000_mph = taxi[trip_mph_bool,5:9]

print(trips_over_20000_mph)
```

```python
[[     2      2     23      1]
 [     2      2   19.6      1]
 [     2      2   16.7      2]
 [     3      3   17.8      2]
 [     2      2   17.2      2]
 [     3      3   16.9      3]
 [     2      2   27.1      4]]
```

<div>
<p>Podemos ver en la última columna que la mayoría de estos son viajes muy cortos: todos tienen valores de <code>trip_length</code> de 4 segundos o menos, lo que no se concilia con las distancias de viaje, que son más de 16 millas.</p>
<p>Usemos esta técnica para examinar las filas que tienen los valores más altos para la columna <code>tip_amount</code>.</p></div>

<h3>Ejercicio</h3>

<ol>
<li>Cree una matriz booleana, <code>tip_bool</code>, que determine qué filas tienen valores para la columna <code>tip_amount</code> de más de <code>50</code>.</li>
<li>Utilice la matriz <code>tip_bool</code> para seleccionar todas las filas de <code>taxi</code> con valores de propina de más de <code>50</code>, y las columnas de los índices 5 a 13 inclusive. Asigne la matriz resultante a <code>top_tips</code>.</li>
</ol>

In [ ]:
tip_amount = taxi[:,12]

<h2>6. Asignación de valores en ndarrays</h2>
<br>
<div><p>Hasta ahora, hemos aprendido a recuperar datos de ndarrays. A continuación, usaremos las mismas técnicas de indexación que ya aprendimos para modificar valores dentro de un ndarray. Esta es la sintaxis que usaremos (en pseudocódigo):</p>
</div>

```python
ndarray[location_of_values] = new_value
```

<div>
<p>Veamos cómo se ve eso en el código real. Con nuestra matriz 1D, podemos especificar una ubicación de índice específica:</p>
</div>

```python
a = np.array(['red','blue','black','blue','purple'])
a[0] = 'orange'
print(a)
```

```python
['orange', 'blue', 'black', 'blue', 'purple']
```

<div>
<p>O podemos asignar varios valores a la vez:</p>
</div>

```python
a[3:] = 'pink'
print(a)
```

```python
['orange', 'blue', 'black', 'pink', 'pink']
```

<div>
<p>Con un ndarray 2D, como con un ndarray 1D, podemos asignar una ubicación de índice específica:</p>
</div>

```python
ones = np.array([[1, 1, 1, 1, 1],
                 [1, 1, 1, 1, 1],
                 [1, 1, 1, 1, 1]])
ones[1,2] = 99
print(ones)
```

```python
[[ 1,  1,  1,  1,  1],
 [ 1,  1, 99,  1,  1],
 [ 1,  1,  1,  1,  1]]
```

<div>
<p>También podemos asignar una fila completa...</p>
</div>

```python
ones[0] = 42
print(ones)
```

```python
[[42, 42, 42, 42, 42],
 [ 1,  1, 99,  1,  1],
 [ 1,  1,  1,  1,  1]]
```


<div>
<p>...o una columna completa:</p>
</div>

```python
ones[:,2] = 0
print(ones)
```

```python
[[42, 42, 0, 42, 42],
 [ 1,  1, 0,  1,  1],
 [ 1,  1, 0,  1,  1]]
```

<div>
<p>Practiquemos algunas asignaciones de matrices con nuestro conjunto de datos de taxis.</p></div>

<h3>Ejercicio</h3>
<br>
<div><p>Para ayudarlo a practicar sin realizar cambios en nuestra matriz original, hemos utilizado  <a href="http://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.ndarray.copy.html#numpy.ndarray.copy" target="_blank">el método <code>ndarray.copy()</code></a> para hacer <code>taxi_modified</code>, una copia de nuestro original para estos ejercicios.</p>
<ol>
<li>El valor del índice de columna <code>5</code> (pickup_location) del índice de fila <code>1066</code> es incorrecto. Use la asignación para cambiar este valor a <code>1</code> en el <code>taxi_modified</code> ndarray.</li>
<li>La primera columna (índice <code>0</code>) contiene valores de año como números de cuatro dígitos en el formato AAAA (<code>2016</code>, ya que todos los viajes en nuestro conjunto de datos son de 2016). Utilice la asignación para cambiar estos valores al formato YY (<code>16</code>) en el <code>taxi_modified</code> ndarray.</li>
<li>Los valores en el índice de columna <code>7</code> (trip_distance) del índice de filas <code>550</code> y <code>551</code> son incorrectos. Utilice la asignación para cambiar estos valores en el ndarray <code>taxi_modified</code> al valor medio de esa columna.</li>
</ol></div>

In [ ]:
taxi_modified = 


<h2>7. Asignación utilizando matrices booleanas</h2>

<br>

<div><p>Las matrices booleanas se vuelven muy poderosas cuando las usamos para la asignación. Veamos un ejemplo:</p>
</div>

```python
a2 = np.array([1, 2, 3, 4, 5])

a2_bool = a2 > 2

a2[a2_bool] = 99

print(a2)
```

```python
[ 1  2 99 99 99]
```

<div>
<p>La matriz booleana controla los valores a los que se aplica la asignación y los demás valores permanecen sin cambios. Veamos cómo funciona este código:</p>
<p><img src="https://s3.amazonaws.com/dq-content/290/bool_assignment_1.svg" alt="Ejemplo de asignación booleana 1" width="600" height="400"></p>
<p>Observe en el diagrama anterior que usamos un "atajo": insertamos la definición de la matriz booleana directamente en la selección. Este "atajo" es la forma convencional de escribir la indexación booleana. Hasta ahora, hemos estado asignando primero a una variable intermedia para que el proceso sea claro, pero de ahora en adelante, usaremos este método de "atajo" en su lugar. </p></div>

<h3>Ejercicio</h3>
<br>
<div><p>Nuevamente usamos el <a href="http://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.ndarray.copy.html#numpy.ndarray.copy" target="_blank">método <code>ndarray.copy()</code> </a> para hacer <code>taxi_copy</code>, una copia de nuestro original para este ejercicio.</p>
<ol>
<li>Seleccione la decimocuarta columna (índice 13) en <code>taxi_copy</code>. Asígnelo a una variable llamada <code>total_amount</code>.</li>
<li>Para las filas donde el valor de <code>total_amount</code> es menor que <code>0</code>, use la asignación para cambiar el valor a <code>0</code>.</li>
</ol></div>

<h2>8. Asignación utilizando matrices booleanas, continuación</h2>
<br>

<div><p>A continuación, veremos un ejemplo de asignación usando una matriz booleana con <em>dos</em> dimensiones:</p>
<p><img src="https://s3.amazonaws.com/dq-content/290/bool_assignment_2.svg" alt="Ejemplo de asignación booleana 2" width="600" height="400"></p>
<p>El <código>b &gt; 4</code> La operación booleana produce una matriz booleana 2D que luego controla los valores a los que se aplica la asignación.</p>
<p>También podemos usar una matriz booleana 1D para realizar asignaciones en una matriz 2D:</p>
<p><img src="https://s3.amazonaws.com/dq-content/290/bool_assignment_3.svg" alt="Ejemplo de asignación booleana 3" width="600" height="400"></p>
<p>El <code>c[:,1] &gt; 2</code> La operación booleana compara solo los valores de una columna y produce una matriz booleana 1D. Luego usamos esa matriz booleana como índice de fila para la asignación y <code>1</code> como índice de columna para especificar la segunda columna. Nuestra matriz booleana solo se aplica a la segunda columna, mientras que todos los demás valores permanecen sin cambios.</p>
<p>La sintaxis del pseudocódigo para este código es la siguiente, primero usando una variable intermedia:</p>
</div>

```python
bool = array[:, column_for_comparison] == value_for_comparison
array[bool, column_for_assignment] = new_value
```


<div>
<p>...y luego todo en una línea:</p>
</div>

```python
array[array[:, column_for_comparison] == value_for_comparison, column_for_assignment] = new_value
```

<div>
<p>Practiquemos este patrón usando nuestro conjunto de datos de taxis:</p></div>

<h3>Ejercicio</h3>
<br>
<div><p>Hemos creado una nueva copia de nuestro conjunto de datos de taxi, <code>taxi_modified</code >, con una columna adicional que contiene el valor <code>0</code> para cada fila.</p>
<ol>
<li>En nuestra nueva columna en el índice <code>15</code>, asigne el valor <code>1</code> si <code>pickup_location_code</code> (índice de columna <code>5</code> ) corresponde a una ubicación de aeropuerto, dejando el valor como <code>0</code> de lo contrario realizando estas tres operaciones:<ul>
<li>Para filas donde el valor del índice de columna <code>5</code> es igual a <code>2</code> (Aeropuerto JFK), asigne el valor <code>1</code> al índice de columna <código>15</código>.</li>
<li>Para filas donde el valor del índice de columna <code>5</code> es igual a <code>3</code> (Aeropuerto LaGuardia), asigne el valor <code>1</code> al índice de columna <código>15</código>.</li>
<li>Para filas donde el valor del índice de columna <code>5</code> es igual a <code>5</code> (Aeropuerto de Newark), asigne el valor <code>1</code> al índice de columna <código>15</código>.</li>
</ul>
</li>
</ol></div>

In [ ]:
# create a new column filled with `0`.


<h2>9. Desafío: ¿Cuál es el aeropuerto más popular?</h2>
<br>
<div><p>Concluiremos esta lección con dos desafíos que te ayudarán a practicar las técnicas que has aprendido en esta lección.</p>
<p>Te proporcionamos varios consejos para ayudarte, pero primero trata de completar el desafío sin los consejos, si puedes. No se desanime si estos pasos del desafío requieren varios intentos: ¡trabajar con datos es un proceso iterativo!</p>
<p>En este desafío, queremos averiguar qué aeropuerto es el destino más popular en nuestro conjunto de datos. Para hacer eso, usaremos la indexación booleana para crear tres matrices filtradas y luego veremos cuántas filas hay en cada matriz. </p>
<p>Para completar esta tarea, debemos verificar si la columna <code>dropoff_location_code</code> (índice de columna <code>6</code>) es igual a uno de los siguientes valores:</p>
<ul>
<li><code>2</code>: Aeropuerto JFK</li>
<li><code>3</code>: Aeropuerto LaGuardia</li>
<li><code>5</code>: Aeropuerto de Newark.</li>
</ul></div>

<h3>Ejercicio</h3>
<br>
<ol>
<li>Usando <code>taxi</code> original, calcule cuántos viajes tuvieron como destino el Aeropuerto JFK:<ul>
<li>Use la indexación booleana para seleccionar solo las filas donde la columna <code>dropoff_location_code</code> (índice de columna <code>6</code>) tiene un valor que corresponde a JFK. Asigne el resultado a <code>jfk</code>.</li>
<li>Calcule cuántas filas hay en la nueva matriz <code>jfk</code> y asigne el resultado a <code>jfk_count</code>.</li>
</ul>
</li>
<li>Calcule cuántos viajes desde <code>taxi</code> tuvieron como destino el Aeropuerto LaGuardia:<ul>
<li>Utilice la indexación booleana para seleccionar solo las filas donde la columna <code>dropoff_location_code</code> (índice de columna <code>6</code>) tiene un valor que corresponde a LaGuardia. Asigne el resultado a <code>laguardia</code>.</li>
<li>Calcule cuántas filas hay en la nueva matriz <code>laguardia</code>. Asigne el resultado a <code>laguardia_count</code>.</li>
</ul>
</li>
<li>Calcule cuántos viajes en taxi tuvieron como destino el aeropuerto de Newark:<ul>
<li>Seleccione solo las filas donde la columna <code>dropoff_location_code</code> tenga un valor que corresponda a Newark y asigne el resultado a <code>newark</code>.</li>
<li>Calcule cuántas filas hay en la nueva matriz <code>newark</code> y asigne el resultado a <code>newark_count</code>.</li>
</ul>
</li>
<li>Después de ejecutar su código, inspeccione los valores de <code>jfk_count</code>, <code>laguardia_count</code> y <code>newark_count</code> y vea qué aeropuerto tiene la mayor cantidad de devoluciones. </li>
</ol>

In [ ]:
dropoff_location_code = 6

In [ ]:
print(f'JFK: {laguardia_count}')
print(f'LaGuardia. {laguardia_count}')
print(f'Newark: {newark_count}')

<h2>10. Desafío: Cálculo de estadísticas de viajes con datos limpios</h2>
<br>
<div><p>Nuestros cálculos en la celda anterior muestran que LaGuardia es el aeropuerto más común para las entregas en nuestro conjunto de datos.</p>
<p>Nuestro segundo y último desafío consiste en eliminar datos potencialmente malos de nuestro conjunto de datos y luego calcular algunas estadísticas descriptivas sobre los datos "limpios" restantes.</p>
<p>Comenzaremos usando la indexación booleana para eliminar las filas que tengan una velocidad promedio para el viaje superior a 160 kph (100 mph), lo que debería eliminar cualquier dato cuestionable. Luego, usaremos métodos de matriz para calcular la media de columnas específicas de los datos restantes. Estas son las columnas que nos interesan:</p>
<ul>
<li><code>trip_distance</code>, en el índice de columna <code>7</code></li>
<li><code>trip_length</code>, en el índice de columna <code>8</code></li>
<li><code>total_amount</code>, en el índice de columna <code>13</code></li>
</ul></div>

<h3>Ejercicio</h3>
<br>
<div><p>Se le proporcionó el <code>trip_mph</code> ndarray.</p>
<ol>
<li>Cree un nuevo ndarray, <code>cleaned_taxi</code>, que contenga solo filas para las que los valores de <code>trip_mph</code> sean inferiores a 100.</li>
<li>Calcule la media de la columna <code>trip_distance</code> de <code>cleaned_taxi</code>. Asigne el resultado a <code>mean_distance</code>.</li>
<li>Calcule la media de la columna <code>trip_length</code> de <code>cleaned_taxi</code>. Asigne el resultado a <code>mean_length</code>.</li>
<li>Calcule la media de la columna <code>total_amount</code> de <code>cleaned_taxi</code>. Asigne el resultado a <code>mean_total_amount</code>.</li>
</ol></div>

In [ ]:
trip_mph = taxi[:,7] / (taxi[:,8] / 3600)

<h2>11. Próximos pasos</h2>
<br>
<div><p>En esta lección aprendimos lo siguiente:</p>
<ul>
<li>Cómo usar <code>numpy.genfromtxt()</code> para leer en un ndarray</li>
<li>Valores NaN</li>
<li>Qué es una matriz booleana y cómo crear una</li>
<li>Cómo usar la indexación booleana para filtrar valores en ndarrays de una y dos dimensiones</li>
<li>Cómo asignar uno o más valores nuevos a un ndarray en función de sus ubicaciones</li>
<li>Cómo asignar uno o más valores nuevos a un ndarray en función de sus valores</li>
</ul>
<p>Esta es la última lección que trata exclusivamente con NumPy, pero ciertamente no es la última vez que usaremos NumPy. A medida que avanzamos en el aprendizaje de otras bibliotecas de datos de Python, se encontrará utilizando muchos de estos conceptos fundamentales de NumPy. También usaremos NumPy de vez en cuando para crear, transformar y trabajar con datos tabulares.</p>
<p>En la próxima lección, comenzaremos a usar la biblioteca pandas y aprenderemos cómo se compara con NumPy.</p></div>